### ISSUE TITLE
试用后觉得很有趣！请问大佬翻译和发音是怎么实现的呢？

### ISSUE THREAD

**Issue by pengp25** [hezhizheng/cantonese-cool#1]
可否方便留个邮箱进行后续的交流，小程序写的很有意思

**Comment by hezhizheng** [comment]
留意下 readme.md 会发现我在下方有致谢 [Ekho](https://www.eguidedog.net/cn/ekho_cn.php) 可自行配置安装 也可直接使用他们的API 具体 可以参考他们的文档 或直接查看本项目的源码 pages/feature/index.vue
